main: me.trumpetplayer2.Pyroshot.PyroshotMain
name: Pyroshot
version: 2.1.2
description: A minigame involving fireballs and a bow.
website: https://www.spigotmc.org/resources/pyroshot-minigame-v2-0.94284/
author: Trumpetplayer2
api-version: 1.19

softdepend: [PlaceholderAPI,ProtocolLib]

commands:
  Pyroshot:
    description: Pyroshot master command.
    usage: /<command> [subcommand]

permissions:
    pyroshot.*:
        description: Pyroshot Wildcard
        default: false
    pyroshot.admin.*:
        description: Pyroshot Admin Wildcard
        default: op
    pyroshot.admin.modifystats:
        description: Allows Admin to change a players Win/Lose stats via a command
        default: op
    pyroshot.admin.pause:
        description: Allows an Admin to pause the autostart
        default: op
    pyroshot.admin.unpause:
        description: Allows an Admin to unpause the autostart
        default: op
    pyroshot.admin.initialize:
        description: Allows an Admin to initialize the game early
        default: op
    pyroshot.admin.start:
        description: Allows an Admin to start the game early
        default: op
    pyroshot.admin.togglepause:
        description: Allows an Admin to toggle between pause/unpausing the autostart
        default: op
    pyroshot.minigame.*:
        description: Pyroshot Minigame Wildcard
    pyroshot.minigame.selectkit:
        description: Allows a user to select a kit in the GUI
        default: true
    pyroshot.minigame.vote:
        description: Allows a player to vote on the map
        default: true
    pyroshot.minigame.votecount:
        description: Allows players to check the map vote counts
        default: op
    pyroshot.minigame.kits.*:
        description: Allows a player to select kit, Each kit has its own permission, wildcard allows all
        default: true